// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi9tBwAH1naa97fLHGtv1bETJD60G72sU',
    appId: '1:174669776651:web:1388f49af25ded8872040e',
    messagingSenderId: '174669776651',
    projectId: 'collegepro-5affd',
    authDomain: 'collegepro-5affd.firebaseapp.com',
    databaseURL: 'https://collegepro-5affd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegepro-5affd.firebasestorage.app',
    measurementId: 'G-H5BLQ97YQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEZMQtJ4GzdbKqvIqWjAvTW90vymYssg',
    appId: '1:174669776651:android:2bc4694df2769d2d72040e',
    messagingSenderId: '174669776651',
    projectId: 'collegepro-5affd',
    databaseURL: 'https://collegepro-5affd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegepro-5affd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlDDudEIPk_-H3cOo5twrBLley2admcHY',
    appId: '1:174669776651:ios:cfec910bbd64309d72040e',
    messagingSenderId: '174669776651',
    projectId: 'collegepro-5affd',
    databaseURL: 'https://collegepro-5affd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegepro-5affd.firebasestorage.app',
    iosBundleId: 'com.example.collegepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlDDudEIPk_-H3cOo5twrBLley2admcHY',
    appId: '1:174669776651:ios:cfec910bbd64309d72040e',
    messagingSenderId: '174669776651',
    projectId: 'collegepro-5affd',
    databaseURL: 'https://collegepro-5affd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegepro-5affd.firebasestorage.app',
    iosBundleId: 'com.example.collegepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi9tBwAH1naa97fLHGtv1bETJD60G72sU',
    appId: '1:174669776651:web:5d9adc49edf6fb7872040e',
    messagingSenderId: '174669776651',
    projectId: 'collegepro-5affd',
    authDomain: 'collegepro-5affd.firebaseapp.com',
    databaseURL: 'https://collegepro-5affd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegepro-5affd.firebasestorage.app',
    measurementId: 'G-ZN1P1SG64V',
  );
}
